Fix timespec/timeval nsec/usec conversion
Explicitly cast conversion result of nsec / 1000 to suseconds_t to
account for possible difference in variable width and signedness as
observed on macOS causing warnings such as:

../libcperciva/util/monoclock.c:36:28: error: implicit conversion loses
integer precision: 'long' to '__darwin_suseconds_t' (aka 'int')
      [-Werror,-Wshorten-64-to-32]
                tv->tv_usec = tp.tv_nsec / 1000;
                            ~ ~~~~~~~~~~~^~~~~~